language: node_js
node_js:
  - '7.8.0'
env:
    global:
        - CHROME_BIN="chromium-browser"
        - DISPLAY=:99.0
        - NODE_ENV=test
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
before_install:
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
branches:
  only:
    - master
    - next
