name: "Test - action"

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install
      run: make install

  build:
    needs: setup
    - run: make build

  lint:
    needs: setup
    - run: make lint

  unit-test:
    needs: build
    steps:
    - run: make test-unit
      env:
        CI: true

  e2e-test:
    needs: build
    steps:
    - run: make test-e2e
      env:
        CI: true

